<?php

namespace Imoing\Pptx\Enum;

use Imoing\Pptx\Enum\Base\TraitXmlEnum;

enum MsoLanguageId : int
{
    use TraitXmlEnum;

    case NONE = 0;
    case AFRIKAANS = 1078;
    case ALBANIAN = 1052;
    case AMHARIC = 1118;
    case ARABIC = 1025;
    case ARABIC_ALGERIA = 5121;
    case ARABIC_BAHRAIN = 15361;
    case ARABIC_EGYPT = 3073;
    case ARABIC_IRAQ = 2049;
    case ARABIC_JORDAN = 11265;
    case ARABIC_KUWAIT = 13313;
    case ARABIC_LEBANON = 12289;
    case ARABIC_LIBYA = 4097;
    case ARABIC_MOROCCO = 6145;
    case ARABIC_OMAN = 8193;
    case ARABIC_QATAR = 16385;
    case ARABIC_SYRIA = 10241;
    case ARABIC_TUNISIA = 7169;
    case ARABIC_UAE = 14337;
    case ARABIC_YEMEN = 9217;
    case ARMENIAN = 1067;
    case ASSAMESE = 1101;
    case AZERI_CYRILLIC = 2092;
    case AZERI_LATIN = 1068;
    case BASQUE = 1069;
    case BELGIAN_DUTCH = 2067;
    case BELGIAN_FRENCH = 2060;
    case BENGALI = 1093;
    case BOSNIAN = 4122;
    case BOSNIAN_BOSNIA_HERZEGOVINA_CYRILLIC = 8218;
    case BOSNIAN_BOSNIA_HERZEGOVINA_LATIN = 5146;
    case BRAZILIAN_PORTUGUESE = 1046;
    case BULGARIAN = 1026;
    case BURMESE = 1109;
    case BYELORUSSIAN = 1059;
    case CATALAN = 1027;
    case CHEROKEE = 1116;
    case CHINESE_HONG_KONG_SAR = 3076;
    case CHINESE_MACAO_SAR = 5124;
    case CHINESE_SINGAPORE = 4100;
    case CROATIAN = 1050;
    case CZECH = 1029;
    case DANISH = 1030;
    case DIVEHI = 1125;
    case DUTCH = 1043;
    case EDO = 1126;
    case ENGLISH_AUS = 3081;
    case ENGLISH_BELIZE = 10249;
    case ENGLISH_CANADIAN = 4105;
    case ENGLISH_CARIBBEAN = 9225;
    case ENGLISH_INDONESIA = 14345;
    case ENGLISH_IRELAND = 6153;
    case ENGLISH_JAMAICA = 8201;
    case ENGLISH_NEW_ZEALAND = 5129;
    case ENGLISH_PHILIPPINES = 13321;
    case ENGLISH_SOUTH_AFRICA = 7177;
    case ENGLISH_TRINIDAD_TOBAGO = 11273;
    case ENGLISH_UK = 2057;
    case ENGLISH_US = 1033;
    case ENGLISH_ZIMBABWE = 12297;
    case ESTONIAN = 1061;
    case FAEROESE = 1080;
    case FARSI = 1065;
    case FILIPINO = 1124;
    case FINNISH = 1035;
    case FRANCH_CONGO_DRC = 9228;
    case FRENCH = 1036;
    case FRENCH_CAMEROON = 11276;
    case FRENCH_CANADIAN = 3084;
    case FRENCH_COTED_IVOIRE = 12300;
    case FRENCH_HAITI = 15372;
    case FRENCH_LUXEMBOURG = 5132;
    case FRENCH_MALI = 13324;
    case FRENCH_MONACO = 6156;
    case FRENCH_MOROCCO = 14348;
    case FRENCH_REUNION = 8204;
    case FRENCH_SENEGAL = 10252;
    case FRENCH_WEST_INDIES = 7180;
    case FRISIAN_NETHERLANDS = 1122;
    case FULFULDE = 1127;
    case GAELIC_IRELAND = 2108;
    case GAELIC_SCOTLAND = 1084;
    case GALICIAN = 1110;
    case GEORGIAN = 1079;
    case GERMAN = 1031;
    case GERMAN_AUSTRIA = 3079;
    case GERMAN_LIECHTENSTEIN = 5127;
    case GERMAN_LUXEMBOURG = 4103;
    case GREEK = 1032;
    case GUARANI = 1140;
    case GUJARATI = 1095;
    case HAUSA = 1128;
    case HAWAIIAN = 1141;
    case HEBREW = 1037;
    case HINDI = 1081;
    case HUNGARIAN = 1038;
    case IBIBIO = 1129;
    case ICELANDIC = 1039;
    case IGBO = 1136;
    case INDONESIAN = 1057;
    case INUKTITUT = 1117;
    case ITALIAN = 1040;
    case JAPANESE = 1041;
    case KANNADA = 1099;
    case KANURI = 1137;
    case KASHMIRI = 1120;
    case KASHMIRI_DEVANAGARI = 2144;
    case KAZAKH = 1087;
    case KHMER = 1107;
    case KIRGHIZ = 1088;
    case KONKANI = 1111;
    case KOREAN = 1042;
    case LAO = 1108;
    case LATIN = 1142;
    case LATVIAN = 1062;
    case LITHUANIAN = 1063;
    case MACEDONINAN_FYROM = 1071;
    case MALAY_BRUNEI_DARUSSALAM = 2110;
    case MALAYALAM = 1100;
    case MALAYSIAN = 1086;
    case MALTESE = 1082;
    case MANIPURI = 1112;
    case MAORI = 1153;
    case MARATHI = 1102;
    case MEXICAN_SPANISH = 2058;
    case MONGOLIAN = 1104;
    case NEPALI = 1121;
    case NO_PROOFING = 1024;
    case NORWEGIAN_BOKMOL = 1044;
    case NORWEGIAN_NYNORSK = 2068;
    case ORIYA = 1096;
    case OROMO = 1138;
    case PASHTO = 1123;
    case POLISH = 1045;
    case PORTUGUESE = 2070;
    case PUNJABI = 1094;
    case QUECHUA_BOLIVIA = 1131;
    case QUECHUA_ECUADOR = 2155;
    case QUECHUA_PERU = 3179;
    case RHAETO_ROMANIC = 1047;
    case ROMANIAN = 1048;
    case ROMANIAN_MOLDOVA = 2072;
    case RUSSIAN = 1049;
    case RUSSIAN_MOLDOVA = 2073;
    case SAMI_LAPPISH = 1083;
    case SANSKRIT = 1103;
    case SEPEDI = 1132;
    case SERBIAN_BOSNIA_HERZEGOVINA_CYRILLIC = 7194;
    case SERBIAN_BOSNIA_HERZEGOVINA_LATIN = 6170;
    case SERBIAN_CYRILLIC = 3098;
    case SERBIAN_LATIN = 2074;
    case SESOTHO = 1072;
    case SIMPLIFIED_CHINESE = 2052;
    case SINDHI = 1113;
    case SINDHI_PAKISTAN = 2137;
    case SINHALESE = 1115;
    case SLOVAK = 1051;
    case SLOVENIAN = 1060;
    case SOMALI = 1143;
    case SORBIAN = 1070;
    case SPANISH = 1034;
    case SPANISH_ARGENTINA = 11274;
    case SPANISH_BOLIVIA = 16394;
    case SPANISH_CHILE = 13322;
    case SPANISH_COLOMBIA = 9226;
    case SPANISH_COSTA_RICA = 5130;
    case SPANISH_DOMINICAN_REPUBLIC = 7178;
    case SPANISH_ECUADOR = 12298;
    case SPANISH_EL_SALVADOR = 17418;
    case SPANISH_GUATEMALA = 4106;
    case SPANISH_HONDURAS = 18442;
    case SPANISH_MODERN_SORT = 3082;
    case SPANISH_NICARAGUA = 19466;
    case SPANISH_PANAMA = 6154;
    case SPANISH_PARAGUAY = 15370;
    case SPANISH_PERU = 10250;
    case SPANISH_PUERTO_RICO = 20490;
    case SPANISH_URUGUAY = 14346;
    case SPANISH_VENEZUELA = 8202;
    case SWAHILI = 1089;
    case SWEDISH = 1053;
    case SWEDISH_FINLAND = 2077;
    case SWISS_FRENCH = 4108;
    case SWISS_GERMAN = 2055;
    case SWISS_ITALIAN = 2064;
    case SYRIAC = 1114;
    case TAJIK = 1064;
    case TAMAZIGHT = 1119;
    case TAMAZIGHT_LATIN = 2143;
    case TAMIL = 1097;
    case TATAR = 1092;
    case TELUGU = 1098;
    case THAI = 1054;
    case TIBETAN = 1105;
    case TIGRIGNA_ERITREA = 2163;
    case TIGRIGNA_ETHIOPIC = 1139;
    case TRADITIONAL_CHINESE = 1028;
    case TSONGA = 1073;
    case TSWANA = 1074;
    case TURKISH = 1055;
    case TURKMEN = 1090;
    case UKRAINIAN = 1058;
    case URDU = 1056;
    case UZBEK_CYRILLIC = 2115;
    case UZBEK_LATIN = 1091;
    case VENDA = 1075;
    case VIETNAMESE = 1066;
    case WELSH = 1106;
    case XHOSA = 1076;
    case YI = 1144;
    case YIDDISH = 1085;
    case YORUBA = 1130;
    case ZULU = 1077;
    case MIXED = -2;

    public static function getXmlValues(): array
    {
        return [
            self::NONE->value => ["", "No language specified."],
            self::AFRIKAANS->value => ["af-ZA", "The Afrikaans language."],
            self::ALBANIAN->value => ["sq-AL", "The Albanian language."],
            self::AMHARIC->value => ["am-ET", "The Amharic language."],
            self::ARABIC->value => ["ar-SA", "The Arabic language."],
            self::ARABIC_ALGERIA->value => ["ar-DZ", "The Arabic Algeria language."],
            self::ARABIC_BAHRAIN->value => ["ar-BH", "The Arabic Bahrain language."],
            self::ARABIC_EGYPT->value => ["ar-EG", "The Arabic Egypt language."],
            self::ARABIC_IRAQ->value => ["ar-IQ", "The Arabic Iraq language."],
            self::ARABIC_JORDAN->value => ["ar-JO", "The Arabic Jordan language."],
            self::ARABIC_KUWAIT->value => ["ar-KW", "The Arabic Kuwait language."],
            self::ARABIC_LEBANON->value => ["ar-LB", "The Arabic Lebanon language."],
            self::ARABIC_LIBYA->value => ["ar-LY", "The Arabic Libya language."],
            self::ARABIC_MOROCCO->value => ["ar-MA", "The Arabic Morocco language."],
            self::ARABIC_OMAN->value => ["ar-OM", "The Arabic Oman language."],
            self::ARABIC_QATAR->value => ["ar-QA", "The Arabic Qatar language."],
            self::ARABIC_SYRIA->value => ["ar-SY", "The Arabic Syria language."],
            self::ARABIC_TUNISIA->value => ["ar-TN", "The Arabic Tunisia language."],
            self::ARABIC_UAE->value => ["ar-AE", "The Arabic UAE language."],
            self::ARABIC_YEMEN->value => ["ar-YE", "The Arabic Yemen language."],
            self::ARMENIAN->value => ["hy-AM", "The Armenian language."],
            self::ASSAMESE->value => ["as-IN", "The Assamese language."],
            self::AZERI_CYRILLIC->value => ["az-AZ", "The Azeri Cyrillic language."],
            self::AZERI_LATIN->value => ["az-Latn-AZ", "The Azeri Latin language."],
            self::BASQUE->value => ["eu-ES", "The Basque language."],
            self::BELGIAN_DUTCH->value => ["nl-BE", "The Belgian Dutch language."],
            self::BELGIAN_FRENCH->value => ["fr-BE", "The Belgian French language."],
            self::BENGALI->value => ["bn-IN", "The Bengali language."],
            self::BOSNIAN->value => ["hr-BA", "The Bosnian language."],
            self::BOSNIAN_BOSNIA_HERZEGOVINA_CYRILLIC->value => ["bs-BA", "The Bosnian Bosnia Herzegovina Cyrillic language."],
            self::BOSNIAN_BOSNIA_HERZEGOVINA_LATIN->value => ["bs-Latn-BA", "The Bosnian Bosnia Herzegovina Latin language."],
            self::BRAZILIAN_PORTUGUESE->value => ["pt-BR", "The Brazilian Portuguese language."],
            self::BULGARIAN->value => ["bg-BG", "The Bulgarian language."],
            self::BURMESE->value => ["my-MM", "The Burmese language."],
            self::BYELORUSSIAN->value => ["be-BY", "The Byelorussian language."],
            self::CATALAN->value => ["ca-ES", "The Catalan language."],
            self::CHEROKEE->value => ["chr-US", "The Cherokee language."],
            self::CHINESE_HONG_KONG_SAR->value => ["zh-HK", "The Chinese Hong Kong SAR language."],
            self::CHINESE_MACAO_SAR->value => ["zh-MO", "The Chinese Macao SAR language."],
            self::CHINESE_SINGAPORE->value => ["zh-SG", "The Chinese Singapore language."],
            self::CROATIAN->value => ["hr-HR", "The Croatian language."],
            self::CZECH->value => ["cs-CZ", "The Czech language."],
            self::DANISH->value => ["da-DK", "The Danish language."],
            self::DIVEHI->value => ["div-MV", "The Divehi language."],
            self::DUTCH->value => ["nl-NL", "The Dutch language."],
            self::EDO->value => ["bin-NG", "The Edo language."],
            self::ENGLISH_AUS->value => ["en-AU", "The English AUS language."],
            self::ENGLISH_BELIZE->value => ["en-BZ", "The English Belize language."],
            self::ENGLISH_CANADIAN->value => ["en-CA", "The English Canadian language."],
            self::ENGLISH_CARIBBEAN->value => ["en-CB", "The English Caribbean language."],
            self::ENGLISH_INDONESIA->value => ["en-ID", "The English Indonesia language."],
            self::ENGLISH_IRELAND->value => ["en-IE", "The English Ireland language."],
            self::ENGLISH_JAMAICA->value => ["en-JA", "The English Jamaica language."],
            self::ENGLISH_NEW_ZEALAND->value => ["en-NZ", "The English NewZealand language."],
            self::ENGLISH_PHILIPPINES->value => ["en-PH", "The English Philippines language."],
            self::ENGLISH_SOUTH_AFRICA->value => ["en-ZA", "The English South Africa language."],
            self::ENGLISH_TRINIDAD_TOBAGO->value => ["en-TT", "The English Trinidad Tobago language."],
            self::ENGLISH_UK->value => ["en-GB", "The English UK language."],
            self::ENGLISH_US->value => ["en-US", "The English US language."],
            self::ENGLISH_ZIMBABWE->value => ["en-ZW", "The English Zimbabwe language."],
            self::ESTONIAN->value => ["et-EE", "The Estonian language."],
            self::FAEROESE->value => ["fo-FO", "The Faeroese language."],
            self::FARSI->value => ["fa-IR", "The Farsi language."],
            self::FILIPINO->value => ["fil-PH", "The Filipino language."],
            self::FINNISH->value => ["fi-FI", "The Finnish language."],
            self::FRANCH_CONGO_DRC->value => ["fr-CD", "The French Congo DRC language."],
            self::FRENCH->value => ["fr-FR", "The French language."],
            self::FRENCH_CAMEROON->value => ["fr-CM", "The French Cameroon language."],
            self::FRENCH_CANADIAN->value => ["fr-CA", "The French Canadian language."],
            self::FRENCH_COTED_IVOIRE->value => ["fr-CI", "The French Coted Ivoire language."],
            self::FRENCH_HAITI->value => ["fr-HT", "The French Haiti language."],
            self::FRENCH_LUXEMBOURG->value => ["fr-LU", "The French Luxembourg language."],
            self::FRENCH_MALI->value => ["fr-ML", "The French Mali language."],
            self::FRENCH_MONACO->value => ["fr-MC", "The French Monaco language."],
            self::FRENCH_MOROCCO->value => ["fr-MA", "The French Morocco language."],
            self::FRENCH_REUNION->value => ["fr-RE", "The French Reunion language."],
            self::FRENCH_SENEGAL->value => ["fr-SN", "The French Senegal language."],
            self::FRENCH_WEST_INDIES->value => ["fr-WINDIES", "The French West Indies language."],
            self::FRISIAN_NETHERLANDS->value => ["fy-NL", "The Frisian Netherlands language."],
            self::FULFULDE->value => ["ff-NG", "The Fulfulde language."],
            self::GAELIC_IRELAND->value => ["ga-IE", "The Gaelic Ireland language."],
            self::GAELIC_SCOTLAND->value => ["en-US", "The Gaelic Scotland language."],
            self::GALICIAN->value => ["gl-ES", "The Galician language."],
            self::GEORGIAN->value => ["ka-GE", "The Georgian language."],
            self::GERMAN->value => ["de-DE", "The German language."],
            self::GERMAN_AUSTRIA->value => ["de-AT", "The German Austria language."],
            self::GERMAN_LIECHTENSTEIN->value => ["de-LI", "The German Liechtenstein language."],
            self::GERMAN_LUXEMBOURG->value => ["de-LU", "The German Luxembourg language."],
            self::GREEK->value => ["el-GR", "The Greek language."],
            self::GUARANI->value => ["gn-PY", "The Guarani language."],
            self::GUJARATI->value => ["gu-IN", "The Gujarati language."],
            self::HAUSA->value => ["ha-NG", "The Hausa language."],
            self::HAWAIIAN->value => ["haw-US", "The Hawaiian language."],
            self::HEBREW->value => ["he-IL", "The Hebrew language."],
            self::HINDI->value => ["hi-IN", "The Hindi language."],
            self::HUNGARIAN->value => ["hu-HU", "The Hungarian language."],
            self::IBIBIO->value => ["ibb-NG", "The Ibibio language."],
            self::ICELANDIC->value => ["is-IS", "The Icelandic language."],
            self::IGBO->value => ["ig-NG", "The Igbo language."],
            self::INDONESIAN->value => ["id-ID", "The Indonesian language."],
            self::INUKTITUT->value => ["iu-Cans-CA", "The Inuktitut language."],
            self::ITALIAN->value => ["it-IT", "The Italian language."],
            self::JAPANESE->value => ["ja-JP", "The Japanese language."],
            self::KANNADA->value => ["kn-IN", "The Kannada language."],
            self::KANURI->value => ["kr-NG", "The Kanuri language."],
            self::KASHMIRI->value => ["ks-Arab", "The Kashmiri language."],
            self::KASHMIRI_DEVANAGARI->value => ["ks-Deva", "The Kashmiri Devanagari language."],
            self::KAZAKH->value => ["kk-KZ", "The Kazakh language."],
            self::KHMER->value => ["kh-KH", "The Khmer language."],
            self::KIRGHIZ->value => ["ky-KG", "The Kirghiz language."],
            self::KONKANI->value => ["kok-IN", "The Konkani language."],
            self::KOREAN->value => ["ko-KR", "The Korean language."],
            self::LAO->value => ["lo-LA", "The Lao language."],
            self::LATIN->value => ["la-Latn", "The Latin language."],
            self::LATVIAN->value => ["lv-LV", "The Latvian language."],
            self::LITHUANIAN->value => ["lt-LT", "The Lithuanian language."],
            self::MACEDONINAN_FYROM->value => ["mk-MK", "The Macedonian FYROM language."],
            self::MALAY_BRUNEI_DARUSSALAM->value => ["ms-BN", "The Malay Brunei Darussalam language."],
            self::MALAYALAM->value => ["ml-IN", "The Malayalam language."],
            self::MALAYSIAN->value => ["ms-MY", "The Malaysian language."],
            self::MALTESE->value => ["mt-MT", "The Maltese language."],
            self::MANIPURI->value => ["mni-IN", "The Manipuri language."],
            self::MAORI->value => ["mi-NZ", "The Maori language."],
            self::MARATHI->value => ["mr-IN", "The Marathi language."],
            self::MEXICAN_SPANISH->value => ["es-MX", "The Mexican Spanish language."],
            self::MONGOLIAN->value => ["mn-MN", "The Mongolian language."],
            self::NEPALI->value => ["ne-NP", "The Nepali language."],
            self::NO_PROOFING->value => ["en-US", "No proofing."],
            self::NORWEGIAN_BOKMOL->value => ["nb-NO", "The Norwegian Bokmol language."],
            self::NORWEGIAN_NYNORSK->value => ["nn-NO", "The Norwegian Nynorsk language."],
            self::ORIYA->value => ["or-IN", "The Oriya language."],
            self::OROMO->value => ["om-Ethi-ET", "The Oromo language."],
            self::PASHTO->value => ["ps-AF", "The Pashto language."],
            self::POLISH->value => ["pl-PL", "The Polish language."],
            self::PORTUGUESE->value => ["pt-PT", "The Portuguese language."],
            self::PUNJABI->value => ["pa-IN", "The Punjabi language."],
            self::QUECHUA_BOLIVIA->value => ["quz-BO", "The Quechua Bolivia language."],
            self::QUECHUA_ECUADOR->value => ["quz-EC", "The Quechua Ecuador language."],
            self::QUECHUA_PERU->value => ["quz-PE", "The Quechua Peru language."],
            self::RHAETO_ROMANIC->value => ["rm-CH", "The Rhaeto Romanic language."],
            self::ROMANIAN->value => ["ro-RO", "The Romanian language."],
            self::ROMANIAN_MOLDOVA->value => ["ro-MO", "The Romanian Moldova language."],
            self::RUSSIAN->value => ["ru-RU", "The Russian language."],
            self::RUSSIAN_MOLDOVA->value => ["ru-MO", "The Russian Moldova language."],
            self::SAMI_LAPPISH->value => ["se-NO", "The Sami Lappish language."],
            self::SANSKRIT->value => ["sa-IN", "The Sanskrit language."],
            self::SEPEDI->value => ["ns-ZA", "The Sepedi language."],
            self::SERBIAN_BOSNIA_HERZEGOVINA_CYRILLIC->value => ["sr-BA", "The Serbian Bosnia Herzegovina Cyrillic language."],
            self::SERBIAN_BOSNIA_HERZEGOVINA_LATIN->value => ["sr-Latn-BA", "The Serbian Bosnia Herzegovina Latin language."],
            self::SERBIAN_CYRILLIC->value => ["sr-SP", "The Serbian Cyrillic language."],
            self::SERBIAN_LATIN->value => ["sr-Latn-CS", "The Serbian Latin language."],
            self::SESOTHO->value => ["st-ZA", "The Sesotho language."],
            self::SIMPLIFIED_CHINESE->value => ["zh-CN", "The Simplified Chinese language."],
            self::SINDHI->value => ["sd-Deva-IN", "The Sindhi language."],
            self::SINDHI_PAKISTAN->value => ["sd-Arab-PK", "The Sindhi Pakistan language."],
            self::SINHALESE->value => ["si-LK", "The Sinhalese language."],
            self::SLOVAK->value => ["sk-SK", "The Slovak language."],
            self::SLOVENIAN->value => ["sl-SI", "The Slovenian language."],
            self::SOMALI->value => ["so-SO", "The Somali language."],
            self::SORBIAN->value => ["wen-DE", "The Sorbian language."],
            self::SPANISH->value => ["es-ES_tradnl", "The Spanish language."],
            self::SPANISH_ARGENTINA->value => ["es-AR", "The Spanish Argentina language."],
            self::SPANISH_BOLIVIA->value => ["es-BO", "The Spanish Bolivia language."],
            self::SPANISH_CHILE->value => ["es-CL", "The Spanish Chile language."],
            self::SPANISH_COLOMBIA->value => ["es-CO", "The Spanish Colombia language."],
            self::SPANISH_COSTA_RICA->value => ["es-CR", "The Spanish Costa Rica language."],
            self::SPANISH_DOMINICAN_REPUBLIC->value => ["es-DO", "The Spanish Dominican Republic language."],
            self::SPANISH_ECUADOR->value => ["es-EC", "The Spanish Ecuador language."],
            self::SPANISH_EL_SALVADOR->value => ["es-SV", "The Spanish El Salvador language."],
            self::SPANISH_GUATEMALA->value => ["es-GT", "The Spanish Guatemala language."],
            self::SPANISH_HONDURAS->value => ["es-HN", "The Spanish Honduras language."],
            self::SPANISH_MODERN_SORT->value => ["es-ES", "The Spanish Modern Sort language."],
            self::SPANISH_NICARAGUA->value => ["es-NI", "The Spanish Nicaragua language."],
            self::SPANISH_PANAMA->value => ["es-PA", "The Spanish Panama language."],
            self::SPANISH_PARAGUAY->value => ["es-PY", "The Spanish Paraguay language."],
            self::SPANISH_PERU->value => ["es-PE", "The Spanish Peru language."],
            self::SPANISH_PUERTO_RICO->value => ["es-PR", "The Spanish Puerto Rico language."],
            self::SPANISH_URUGUAY->value => ["es-UR", "The Spanish Uruguay language."],
            self::SPANISH_VENEZUELA->value => ["es-VE", "The Spanish Venezuela language."],
            self::SWAHILI->value => ["sw-KE", "The Swahili language."],
            self::SWEDISH->value => ["sv-SE", "The Swedish language."],
            self::SWEDISH_FINLAND->value => ["sv-FI", "The Swedish Finland language."],
            self::SWISS_FRENCH->value => ["fr-CH", "The Swiss French language."],
            self::SWISS_GERMAN->value => ["de-CH", "The Swiss German language."],
            self::SWISS_ITALIAN->value => ["it-CH", "The Swiss Italian language."],
            self::SYRIAC->value => ["syr-SY", "The Syriac language."],
            self::TAJIK->value => ["tg-TJ", "The Tajik language."],
            self::TAMAZIGHT->value => ["tzm-Arab-MA", "The Tamazight language."],
            self::TAMAZIGHT_LATIN->value => ["tmz-DZ", "The Tamazight Latin language."],
            self::TAMIL->value => ["ta-IN", "The Tamil language."],
            self::TATAR->value => ["tt-RU", "The Tatar language."],
            self::TELUGU->value => ["te-IN", "The Telugu language."],
            self::THAI->value => ["th-TH", "The Thai language."],
            self::TIBETAN->value => ["bo-CN", "The Tibetan language."],
            self::TIGRIGNA_ERITREA->value => ["ti-ER", "The Tigrigna Eritrea language."],
            self::TIGRIGNA_ETHIOPIC->value => ["ti-ET", "The Tigrigna Ethiopic language."],
            self::TRADITIONAL_CHINESE->value => ["zh-TW", "The Traditional Chinese language."],
            self::TSONGA->value => ["ts-ZA", "The Tsonga language."],
            self::TSWANA->value => ["tn-ZA", "The Tswana language."],
            self::TURKISH->value => ["tr-TR", "The Turkish language."],
            self::TURKMEN->value => ["tk-TM", "The Turkmen language."],
            self::UKRAINIAN->value => ["uk-UA", "The Ukrainian language."],
            self::URDU->value => ["ur-PK", "The Urdu language."],
            self::UZBEK_CYRILLIC->value => ["uz-UZ", "The Uzbek Cyrillic language."],
            self::UZBEK_LATIN->value => ["uz-Latn-UZ", "The Uzbek Latin language."],
            self::VENDA->value => ["ve-ZA", "The Venda language."],
            self::VIETNAMESE->value => ["vi-VN", "The Vietnamese language."],
            self::WELSH->value => ["cy-GB", "The Welsh language."],
            self::XHOSA->value => ["xh-ZA", "The Xhosa language."],
            self::YI->value => ["ii-CN", "The Yi language."],
            self::YIDDISH->value => ["yi-Hebr", "The Yiddish language."],
            self::YORUBA->value => ["yo-NG", "The Yoruba language."],
            self::ZULU->value => ["zu-ZA", "The Zulu language."],
            self::MIXED->value => ["", "More than one language in specified range (read-only)."],
        ];
    }
}